### ISSUE TITLE
Do not leave when the queue ends

### ISSUE THREAD

**Issue by LoganTann** [Tetracyl/EarTensifier#116]
Hello,
When the queue is over, the bot automatically leaves the voice channel, even if other users are connected.

Is it possible to make the bot wait one minute before leaving ? This allows people in the voice room to have some time to add music.

## steps to reproduce
* `/join`
* `/play <some music>`
* wait until the queue ends
* bot disconnects instantly

**Comment by Tetracyl** [comment]
Thank you for the feature request, is has been implemented in https://github.com/Tetracyl/EarTensifier/commit/a4f449c6569cec57a801ebb92327946e7162ecae and will be live soon.
