### ISSUE TITLE
Support for traditional, prefixed messages commands

### ISSUE THREAD

**Issue by LoganTann** [Tetracyl/EarTensifier#117]
Hello again,

This is a really debatable thought, but is it possible to command the bot with a prefixed message (such as `.play`) instead of an interaction (`/play`)

Message commands, although not documented or autocompleted, are more ergonomic (especially on mobile) and can be copied and pasted

Thanks in advance!

**Comment by Tetracyl** [comment]
The bot's default prefix is `ear ` and can be changed using the `ear prefix .` command. However, Discord will remove prefixed message commands from all bots without the message intent after April so they will stop working (you will still be able to ping the bot for commands though).

Let me know if this answers your question.

**Comment by LoganTann** [comment]
Oh, I see
thanks a lot for the quick anwser !!
