### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#183]
Please slash command ear shards

**Comment by Tetracyl** [comment]
It's already a slash command but I'm planning on removing it.

**Comment by LoryPelli** [comment]
> It's already a slash command but I'm planning on removing it.

Please don't do it, I love slash commands

**Comment by Tetracyl** [comment]
I am going to do it 👿👿👿👿👿👿👿

**Comment by LoryPelli** [comment]
> I am going to do it 👿👿👿👿👿👿👿

Sad... slash commands are better...

**Comment by Tetracyl** [comment]
Better in what sense? They are 10x slower than normal commands and are clunky and difficult to use.

**Comment by LoryPelli** [comment]
> Better in what sense? They are 10x slower than normal commands and are clunky and difficult to use.

idk why you said slow, they are fast (except with supercell api) and for some commands they are better
