### ISSUE TITLE
if you unloop the song, the song remain looped with the button

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#187]
if you unloop the song, the song remain looped with the button

**Comment by Tetracyl** [comment]
This is because the loop commands don't update the now playing embed. I'll think about it whether or not I want to fix this since it might case more issues with ratelimits.

**Comment by LoryPelli** [comment]
> This is because the loop commands don't update the now playing embed. I'll think about it whether or not I want to fix this since it might case more issues with ratelimits.

But after the song end, the bot play it again also if it's not anymore looped

**Comment by Tetracyl** [comment]
Yes because you override the loop button with the command

**Comment by LoryPelli** [comment]
> Yes because you override the loop button with the command

ehm... I never used the loop command, only the button

**Comment by Tetracyl** [comment]
Can you send a video or screenshot of what you're doing.

**Comment by LoryPelli** [comment]
ok, it seems that the song continue to be looped only for some seconds

**Comment by Tetracyl** [comment]
Fixed in 2.3.1
