### ISSUE TITLE
If there is anything before the song is currently playing in the queue, if you press the button to go to the previous song, it will says interaction failed

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#188]
If there is anything before the song is currently playing in the queue, if you press the button to go to the previous song, it will says interaction failed

**Comment by Tetracyl** [comment]
![image](https://user-images.githubusercontent.com/29833473/188013386-f213f22f-e173-4a41-8402-2a6eeabca698.png)
Previous button works perfectly fine

**Comment by LoryPelli** [comment]
obviously, the button won't work, but it should said a message at least

**Comment by Tetracyl** [comment]
Ok

**Comment by Tetracyl** [comment]
Fixed in 2.3.1
