### ISSUE TITLE
This isn't the song I'm trying to queue

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#189]
![image](https://user-images.githubusercontent.com/87276663/188015857-dd41c6f4-7ecc-415d-bd4c-68e701e88ceb.png)
I'm trying to queue SOLDI but it queue CARA LEGGENDARIA

**Comment by Tetracyl** [comment]
Youtube issue 
![image](https://user-images.githubusercontent.com/29833473/188330156-9a756a2f-20b0-43a8-a679-d271fa3ca7e5.png)
