### ISSUE TITLE
Try using the play app command on a playlist (bot playlist with the view command) it will queue a random song and the queue immidiatly end

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#194]
![image](https://user-images.githubusercontent.com/87276663/188076929-06d34291-501e-4d54-a964-8d61d28cac3e.png)

**Comment by Tetracyl** [comment]
The play modal only allows you to queue up songs, not playlists. Read what it says carefully.
![image](https://user-images.githubusercontent.com/29833473/188285408-69c5f6a0-0755-49a3-8a7b-17b19238d797.png)

**Comment by LoryPelli** [comment]
> The play modal only allows you to queue up songs, not playlists. Read what it says carefully. ![image](https://user-images.githubusercontent.com/29833473/188285408-69c5f6a0-0755-49a3-8a7b-17b19238d797.png)

Not the play modal, the context menu, can you please make that if we use it on something invalid, it will says error?

**Comment by Tetracyl** [comment]
I don't get what's the issue, how would the bot know if you're trying to play a song or playlist. This is the intended behavior.

**Comment by LoryPelli** [comment]
I saw just now that if you use the play context menu on an embed, this happened
