### ISSUE TITLE
Are you sure?

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#195]
![image](https://user-images.githubusercontent.com/87276663/188087074-b556f3b3-2ad0-4004-bbb2-ecbc9d337ada.png)

**Comment by LoryPelli** [comment]
Also I tried to queue a song before, but the queue end istantly

**Comment by LoryPelli** [comment]
And also buttons now says interaction failed

**Comment by LoryPelli** [comment]
![image](https://user-images.githubusercontent.com/87276663/188087580-b9f811f5-cf1d-46df-9388-e3b5ece695b8.png)

**Comment by LoryPelli** [comment]
Now it seems fixed but you should check

**Comment by LoryPelli** [comment]
![image](https://user-images.githubusercontent.com/87276663/188099220-898fb36b-9a01-4386-86c8-c321e0add6e3.png)
Broken again for two times

**Comment by Tetracyl** [comment]
I don't get what the issue is. Please give the issue a proper title and description. Are you sure? is not a proper title
