### ISSUE TITLE
I added 2 songs in the queue. the looped the queue but when the seconds song started I unlooped it but the bot play again the first song of the queue also if it shouldn't do this

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#196]
![image](https://user-images.githubusercontent.com/87276663/188259415-1e4386cd-2fb6-4277-a80f-a1ce0db6deb0.png)
I used the play command, when the first song started, I looped the queue with the button, when the second song started, I unlooped the queue with the button but the bot played again the first song of the queue also if the queue wasn’t looped.

**Comment by LoryPelli** [comment]
Ok, I tested again and it happened again, as I saw, it probably unloop the song but not the queue for some reasons

**Comment by LoryPelli** [comment]
It happens also with the button

**Comment by LoryPelli** [comment]
> It happens also with the button

Sorry, the command I meant

**Comment by Tetracyl** [comment]
I could not reproduce this issue. Please update this issue's description with the exact commands you ran so I can reproduce the bug.

**Comment by LoryPelli** [comment]
> I could not reproduce this issue. Please update this issue's description with the exact commands you ran so I can reproduce the bug.

Done
