### ISSUE TITLE
Add ephemeral messages for button errors

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#199]
Does the bot send an ephemeral message if you try to interact with another user embeds? If no, you should make it

**Comment by Tetracyl** [comment]
What is another user embed

**Comment by LoryPelli** [comment]
> What is another user embed

For exaple if you play a song, your now play embed, if I interact with it, it will says interaction failed, you should made an ephemeral message that said I can't interact with it, idk if also other types of embeds need this

**Comment by Tetracyl** [comment]
You should be able to interact with it though

**Comment by LoryPelli** [comment]
> You should be able to interact with it though


https://user-images.githubusercontent.com/87276663/188332270-37d2e3c3-a221-4a56-ac09-f4d7fd88f09b.mp4

No I'm not, it says interaction failed

**Comment by Tetracyl** [comment]
Added in 2.3.1
