### ISSUE TITLE
Volume command if nothing it's playing

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#200]
If you use the volume command, the bot will says you need to play a song first, but if you use it with a value, the bot will says error
You need to be in the same voice channel as the bot

**Comment by Tetracyl** [comment]
![image](https://user-images.githubusercontent.com/29833473/188330188-87d071af-9079-4c37-b5bd-63b6dce5b727.png)

**Comment by LoryPelli** [comment]
> ![image](https://user-images.githubusercontent.com/29833473/188330188-87d071af-9079-4c37-b5bd-63b6dce5b727.png)

I forgot to says that you need to be in a voice channel

**Comment by Tetracyl** [comment]
Fixed in 2.3.1
