### ISSUE TITLE
play spotify playlist limited to 100 songs

### ISSUE THREAD

**Issue by HysMX** [Tetracyl/EarTensifier#22]
Even tho i added the guild as a "pro" guild the play spotify playlist only returns 100 of the songs in the playlist.

I can add more than 100 songs into queue but the playlist is limited somehow.

**Comment by Tetracyl** [comment]
Spotify API only provides 100 songs which is why the bot returns 100 of the songs in the playlist. If you find a fix/work around feel free to do a PR.

**Comment by HysteriaMC** [comment]
Using the Spotify Web Api  you can set an offset to get the rest of the songs, i'll see if i can make it done and make a PR!
