### ISSUE TITLE
Make a fix command

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#223]
The bot will try something to fix issues

**Comment by Tetracyl** [comment]
Would be impossible for me to code somethign like this

**Comment by LoryPelli** [comment]
> Would be impossible for me to code somethign like this

If it's difficult for you, the command would be only that the bot tries to change voice region or force disconnect himself from the vc

**Comment by LoryPelli** [comment]
> I can do that stuff with eval already

Yes, but I mean a fix command for everyone if the bot is stucked on playing the song, some bots have it
