### ISSUE TITLE
File link command

### ISSUE THREAD

**Issue by LoryPelli** [Tetracyl/EarTensifier#227]
![image](https://user-images.githubusercontent.com/87276663/189075792-a26e4ff2-a837-4707-bbc2-ac5a1a3c495f.png)
This happens if you queue not local files

**Comment by LoryPelli** [comment]
![image](https://user-images.githubusercontent.com/87276663/189076262-3266abc0-fa52-4e81-8d19-421d7254ec72.png)
I can't queue a youtube video

**Comment by Tetracyl** [comment]
I don't understand what's the issue
