### ISSUE TITLE
Update From Erela to Shoukaku 

### ISSUE THREAD

**Issue by rajamoulimallareddy** [Tetracyl/EarTensifier#49]
Use Shoukaku just a suggestion.

**Comment by Tetracyl** [comment]
What does Shoukaku have that erela does not?

**Comment by rajamoulimallareddy** [comment]
> What does Shoukaku have that erela does not?

it is faster and stable than erela As far as I observed.

**Comment by Tetracyl** [comment]
Closing this since I don't plan on changing from erela right now
