### ISSUE TITLE
Violation of the General Public License.

### ISSUE THREAD

**Issue by Anctoesent** [Tetracyl/EarTensifier#99]
The README contains the following quote:

> Ear Tensifier is open source to allow people to contribute to the bot, gain inspiration/ideas from the bot's code, or host a private version of the bot for their own use. You may NOT however host your own clone of Ear Tensifier publicly or list your clone on bot list.

This is against the GPL, which you licensed the bot under, which says:

> All other non-permissive additional terms are considered "further restrictions" within the meaning of section 10.  If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a furtherrestriction, you may remove that term.

GPL cannot be retroactively revoked (so is the nature of copyleft, as the GPL is explicity a concession of full control in the name of the community), so if you want to make your bot visible-source (not "open source", as the Open Source Initiative trademark grant requires full freedoms of redistribution for a program to call itself "open-source"), then change the license it is under. Again, you cannot do this retroactively, so the last commit before relicensing is still GPL.

I recommend you familiarize yourself with these licenses before you adopt another one that invalidates your restrictions.

**Comment by Tetracyl** [comment]
So there is nothing I can do if I wanted to prevent people from ripping off the bot's code and claiming it as their own?

**Comment by Tetracyl** [comment]
I have removed the note in the README

**Comment by Anctoesent** [comment]
You can stop people from calling it as their own, but they can make clones with a different name. So if I were you I'd just add a note asking to not use the name "Ear Tensifier" in forks of the bot.
